#!/usr/bin/env node
const BASE = "https://wqlselfapnggxxeziruo.supabase.co/rest/v1";
const SKEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxbHNlbGZhcG5nZ3h4ZXppcnVvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDEzMzEzOCwiZXhwIjoyMDg5NzA5MTM4fQ.-84Rvf9WHfZzEZl9X2BRfn8ctS04Zb8NVfSy90DlWxc";
const H = {"apikey":SKEY,"Authorization":"Bearer "+SKEY,"Content-Type":"application/json","Prefer":"return=representation"};
const Hm = {"apikey":SKEY,"Authorization":"Bearer "+SKEY,"Content-Type":"application/json","Prefer":"return=minimal"};

const sessions = [
  // =============================================
  // IA - Fundamentos de Programacion (sesiones 9-16)
  // =============================================
  {subjectId:"0df94819-8ccc-499b-ae88-7ed70713295d",number:9,title:"Manejo de archivos: open, read, write, with",video:"https://www.youtube.com/watch?v=Kf4zcmRTEOg",
   theory:"# Manejo de Archivos en Python\n\nPython permite leer y escribir archivos de texto y binarios con funciones nativas.\n\n## Abrir archivos\n```python\narchivo = open(\"datos.txt\", \"r\")\ncontenido = archivo.read()\narchivo.close()\n```\n\n## Modos de apertura\n- `r` - lectura (por defecto)\n- `w` - escritura (sobreescribe)\n- `a` - agregar al final\n- `r+` - lectura y escritura\n- `rb` / `wb` - modo binario\n\n## Context Manager (with)\nLa forma recomendada es usar `with`, que cierra el archivo automaticamente:\n```python\nwith open(\"datos.txt\", \"r\") as f:\n    contenido = f.read()\n# El archivo se cierra solo al salir del bloque\n```\n\n## Escribir archivos\n```python\nwith open(\"salida.txt\", \"w\") as f:\n    f.write(\"Primera linea\\n\")\n    f.write(\"Segunda linea\\n\")\n```\n\n## Leer linea por linea\n```python\nwith open(\"datos.txt\") as f:\n    for linea in f:\n        print(linea.strip())\n```\n\n## Metodos utiles\n- `read()` - lee todo el contenido\n- `readline()` - lee una linea\n- `readlines()` - retorna lista de lineas\n- `write()` - escribe texto\n- `writelines()` - escribe lista de strings",
   quiz:[{q:"Cual es la forma recomendada de abrir archivos?",a:"open() sin cerrar",b:"with open() as f:",c:"file.open()",d:"import file",correct:"b",exp:"with open() cierra automaticamente al terminar el bloque."},
   {q:"Que modo sobreescribe el archivo?",a:"r",b:"a",c:"w",d:"r+",correct:"c",exp:"El modo w sobreescribe todo el contenido existente."},
   {q:"Que hace readlines()?",a:"Lee una linea",b:"Retorna lista de todas las lineas",c:"Cuenta lineas",d:"Lee solo la ultima linea",correct:"b",exp:"readlines() retorna una lista donde cada elemento es una linea."},
   {q:"Para agregar al final de un archivo se usa modo:",a:"w",b:"r+",c:"a",d:"x",correct:"c",exp:"El modo a (append) agrega contenido al final sin borrar lo existente."},
   {q:"Que pasa si no cierras un archivo abierto con open()?",a:"Nada",b:"Error inmediato",c:"Se puede perder datos o bloquear el archivo",d:"Python lo cierra solo",correct:"c",exp:"No cerrar puede causar perdida de datos en buffer o bloqueo del recurso."}]},

  {subjectId:"0df94819-8ccc-499b-ae88-7ed70713295d",number:10,title:"Manejo de errores: try, except, finally",video:"https://www.youtube.com/watch?v=HQqqNBZosn8",
   theory:"# Manejo de Errores en Python\n\nLos errores en tiempo de ejecucion se llaman excepciones. Python permite capturarlas para que el programa no se detenga.\n\n## try / except\n```python\ntry:\n    numero = int(input(\"Ingresa un numero: \"))\n    resultado = 10 / numero\nexcept ValueError:\n    print(\"No ingresaste un numero valido\")\nexcept ZeroDivisionError:\n    print(\"No puedes dividir por cero\")\n```\n\n## except generico\n```python\ntry:\n    # codigo riesgoso\n    pass\nexcept Exception as e:\n    print(\"Error: \" + str(e))\n```\n\n## finally\nSe ejecuta SIEMPRE, haya o no error:\n```python\ntry:\n    archivo = open(\"datos.txt\")\n    datos = archivo.read()\nexcept FileNotFoundError:\n    print(\"Archivo no encontrado\")\nfinally:\n    print(\"Bloque finally ejecutado\")\n```\n\n## else\nSe ejecuta solo si NO hubo error:\n```python\ntry:\n    resultado = 10 / 2\nexcept ZeroDivisionError:\n    print(\"Error\")\nelse:\n    print(\"Todo bien, resultado: \" + str(resultado))\n```\n\n## Excepciones comunes\n- `ValueError` - valor incorrecto\n- `TypeError` - tipo incorrecto\n- `FileNotFoundError` - archivo no existe\n- `KeyError` - clave no existe en diccionario\n- `IndexError` - indice fuera de rango\n\n## Lanzar excepciones\n```python\ndef dividir(a, b):\n    if b == 0:\n        raise ValueError(\"Divisor no puede ser cero\")\n    return a / b\n```",
   quiz:[{q:"Que bloque captura errores en Python?",a:"catch",b:"except",c:"error",d:"handle",correct:"b",exp:"En Python se usa except (no catch como en otros lenguajes)."},
   {q:"finally se ejecuta:",a:"Solo si hay error",b:"Solo si no hay error",c:"Siempre, haya o no error",d:"Nunca automaticamente",correct:"c",exp:"finally se ejecuta siempre, es ideal para limpieza de recursos."},
   {q:"Que excepcion genera int('abc')?",a:"TypeError",b:"ValueError",c:"SyntaxError",d:"NameError",correct:"b",exp:"ValueError porque 'abc' no es un valor numerico valido."},
   {q:"Que hace raise?",a:"Captura error",b:"Ignora error",c:"Lanza una excepcion manualmente",d:"Termina programa",correct:"c",exp:"raise permite lanzar excepciones de forma explicita."},
   {q:"Cuando se ejecuta el bloque else en try/except?",a:"Siempre",b:"Solo si hubo error",c:"Solo si NO hubo error",d:"Despues de finally",correct:"c",exp:"else se ejecuta unicamente si el bloque try no genero ninguna excepcion."}]},

  {subjectId:"0df94819-8ccc-499b-ae88-7ed70713295d",number:11,title:"Modulos y paquetes: import, pip, venv",video:"https://www.youtube.com/watch?v=Zf9sJgFMpOE",
   theory:"# Modulos y Paquetes en Python\n\nLos modulos permiten organizar y reutilizar codigo en archivos separados.\n\n## Importar modulos\n```python\nimport math\nprint(math.sqrt(16))  # 4.0\n\nfrom math import pi, sqrt\nprint(pi)  # 3.14159...\n\nimport math as m\nprint(m.factorial(5))  # 120\n```\n\n## Crear tu propio modulo\nCualquier archivo .py es un modulo:\n```python\n# mi_modulo.py\ndef saludar(nombre):\n    return \"Hola, \" + nombre\n\n# main.py\nfrom mi_modulo import saludar\nprint(saludar(\"Carlos\"))\n```\n\n## pip - Gestor de paquetes\npip instala paquetes de terceros desde PyPI:\n```bash\npip install pandas\npip install numpy matplotlib\npip list\npip freeze > requirements.txt\npip install -r requirements.txt\n```\n\n## Entornos virtuales (venv)\nAislan dependencias por proyecto:\n```bash\npython -m venv mi_entorno\nsource mi_entorno/bin/activate  # Linux/Mac\nmi_entorno\\Scripts\\activate     # Windows\npip install pandas\ndeactivate\n```\n\n## Paquetes populares\n- `numpy` - computacion numerica\n- `pandas` - analisis de datos\n- `matplotlib` - graficos\n- `requests` - peticiones HTTP\n- `flask` - web framework\n\n## __name__ == \"__main__\"\n```python\nif __name__ == \"__main__\":\n    # Solo se ejecuta si corres este archivo directamente\n    print(\"Ejecutando como script principal\")\n```",
   quiz:[{q:"Que es un modulo en Python?",a:"Una funcion especial",b:"Un archivo .py con codigo reutilizable",c:"Un tipo de dato",d:"Una clase interna",correct:"b",exp:"Cualquier archivo .py puede actuar como un modulo importable."},
   {q:"Que hace pip install pandas?",a:"Crea un modulo pandas",b:"Descarga e instala el paquete pandas desde PyPI",c:"Actualiza Python",d:"Crea entorno virtual",correct:"b",exp:"pip descarga e instala paquetes del repositorio PyPI."},
   {q:"Para que sirve venv?",a:"Ejecutar mas rapido",b:"Aislar dependencias por proyecto",c:"Comprimir archivos",d:"Conectar a internet",correct:"b",exp:"venv crea un entorno aislado para que cada proyecto tenga sus propias dependencias."},
   {q:"Que hace from math import sqrt?",a:"Importa todo math",b:"Solo importa la funcion sqrt",c:"Crea modulo math",d:"Importa sqrt de otro archivo",correct:"b",exp:"Importa solo la funcion especifica, sin necesidad de usar math.sqrt()."},
   {q:"Que verifica __name__ == '__main__'?",a:"Si hay errores",b:"Si el archivo se ejecuta directamente (no importado)",c:"Si el modulo existe",d:"Si Python esta instalado",correct:"b",exp:"Permite distinguir si el archivo se ejecuta como script principal o fue importado."}]},

  {subjectId:"0df94819-8ccc-499b-ae88-7ed70713295d",number:12,title:"Programacion orientada a objetos basica: clases y objetos",video:"https://www.youtube.com/watch?v=ZSEgmBGPRqU",
   theory:"# Programacion Orientada a Objetos (POO)\n\nLa POO organiza el codigo alrededor de objetos que combinan datos y comportamiento.\n\n## Clases y Objetos\nUna clase es un molde, un objeto es una instancia:\n```python\nclass Persona:\n    def __init__(self, nombre, edad):\n        self.nombre = nombre\n        self.edad = edad\n    \n    def saludar(self):\n        return \"Hola, soy \" + self.nombre\n\n# Crear objeto\np1 = Persona(\"Maria\", 25)\nprint(p1.saludar())  # Hola, soy Maria\nprint(p1.edad)       # 25\n```\n\n## __init__ (Constructor)\nMetodo especial que se ejecuta al crear un objeto. Inicializa atributos.\n\n## self\nReferencia al objeto actual. Siempre es el primer parametro de los metodos.\n\n## Atributos y Metodos\n- **Atributos**: variables del objeto (self.nombre)\n- **Metodos**: funciones del objeto (def saludar)\n\n## Atributos de clase vs instancia\n```python\nclass Contador:\n    total = 0  # atributo de clase (compartido)\n    \n    def __init__(self):\n        Contador.total += 1\n        self.id = Contador.total  # atributo de instancia\n```\n\n## Metodos especiales\n```python\ndef __str__(self):\n    return self.nombre + \" (\" + str(self.edad) + \" anios)\"\n\ndef __len__(self):\n    return self.edad\n```\n\n## Principios de POO\n- **Encapsulamiento**: datos protegidos dentro del objeto\n- **Abstraccion**: ocultar complejidad interna\n- **Herencia**: crear clases basadas en otras\n- **Polimorfismo**: mismo metodo, diferente comportamiento",
   quiz:[{q:"Que es una clase en Python?",a:"Una funcion grande",b:"Un molde para crear objetos",c:"Un tipo de variable",d:"Un modulo especial",correct:"b",exp:"La clase define la estructura y comportamiento que tendran sus objetos."},
   {q:"Que hace __init__?",a:"Destruye el objeto",b:"Inicializa atributos al crear el objeto",c:"Importa modulos",d:"Define la clase",correct:"b",exp:"__init__ es el constructor que se ejecuta automaticamente al crear una instancia."},
   {q:"Que representa self?",a:"La clase en general",b:"El objeto actual (la instancia)",c:"Una variable global",d:"Un parametro opcional",correct:"b",exp:"self es la referencia al objeto especifico que esta llamando al metodo."},
   {q:"Diferencia entre atributo de clase y de instancia?",a:"No hay diferencia",b:"Clase es compartido, instancia es unico por objeto",c:"Instancia es compartido",d:"Clase no existe en Python",correct:"b",exp:"Atributos de clase se comparten entre todas las instancias; los de instancia son propios de cada objeto."},
   {q:"Cuantos principios fundamentales tiene la POO?",a:"2",b:"3",c:"4",d:"5",correct:"c",exp:"Los 4 principios son: encapsulamiento, abstraccion, herencia y polimorfismo."}]},

  {subjectId:"0df94819-8ccc-499b-ae88-7ed70713295d",number:13,title:"Herencia y polimorfismo",video:"https://www.youtube.com/watch?v=HeEqI7-pRGo",
   theory:"# Herencia y Polimorfismo\n\n## Herencia\nPermite crear nuevas clases basadas en clases existentes, reutilizando codigo.\n\n```python\nclass Animal:\n    def __init__(self, nombre):\n        self.nombre = nombre\n    \n    def hablar(self):\n        return \"...\"\n\nclass Perro(Animal):\n    def hablar(self):\n        return self.nombre + \" dice: Guau!\"\n\nclass Gato(Animal):\n    def hablar(self):\n        return self.nombre + \" dice: Miau!\"\n\nperro = Perro(\"Rex\")\nprint(perro.hablar())  # Rex dice: Guau!\n```\n\n## super()\nLlama al metodo de la clase padre:\n```python\nclass Estudiante(Persona):\n    def __init__(self, nombre, edad, carrera):\n        super().__init__(nombre, edad)\n        self.carrera = carrera\n```\n\n## Polimorfismo\nMismo metodo, diferente comportamiento segun la clase:\n```python\nanimales = [Perro(\"Rex\"), Gato(\"Luna\"), Perro(\"Max\")]\nfor animal in animales:\n    print(animal.hablar())  # Cada uno responde diferente\n```\n\n## Herencia multiple\n```python\nclass Anfibio(Animal, Nadador):\n    pass\n```\n\n## isinstance() y issubclass()\n```python\nprint(isinstance(perro, Animal))     # True\nprint(issubclass(Perro, Animal))     # True\n```\n\n## Metodos y atributos protegidos\n- `_protegido` - convencion (se puede acceder pero no deberia)\n- `__privado` - name mangling (dificil acceder desde fuera)",
   quiz:[{q:"Que es herencia en POO?",a:"Copiar codigo manualmente",b:"Crear clases basadas en otras existentes",c:"Importar modulos",d:"Usar funciones globales",correct:"b",exp:"Herencia permite que una clase hija reutilice atributos y metodos de la clase padre."},
   {q:"Que hace super().__init__()?",a:"Crea nuevo objeto",b:"Llama al constructor de la clase padre",c:"Elimina el objeto",d:"Reemplaza la clase padre",correct:"b",exp:"super() permite acceder a metodos de la clase padre, incluyendo su constructor."},
   {q:"Que es polimorfismo?",a:"Herencia multiple",b:"Mismo metodo, comportamiento diferente segun la clase",c:"Variables con muchos tipos",d:"Multiples constructores",correct:"b",exp:"Polimorfismo permite que objetos de diferentes clases respondan al mismo metodo de formas distintas."},
   {q:"class Gato(Animal) significa:",a:"Gato contiene a Animal",b:"Gato hereda de Animal",c:"Gato reemplaza Animal",d:"Animal hereda de Gato",correct:"b",exp:"Los parentesis indican que Gato es una subclase que hereda de Animal."},
   {q:"Que indica un atributo con doble guion bajo __privado?",a:"Es constante",b:"Es obligatorio",c:"Name mangling, dificil acceder desde fuera",d:"Es estatico",correct:"c",exp:"Python aplica name mangling para dificultar el acceso externo a atributos con __."}]},

  {subjectId:"0df94819-8ccc-499b-ae88-7ed70713295d",number:14,title:"Proyecto: calculadora con funciones",video:"https://www.youtube.com/watch?v=HYrP6hqa1Kw",
   theory:"# Proyecto: Calculadora con Funciones\n\nEn este proyecto construiremos una calculadora completa usando funciones, validacion de entrada y un menu interactivo.\n\n## Estructura del proyecto\n```python\ndef sumar(a, b):\n    return a + b\n\ndef restar(a, b):\n    return a - b\n\ndef multiplicar(a, b):\n    return a * b\n\ndef dividir(a, b):\n    if b == 0:\n        return \"Error: division por cero\"\n    return a / b\n\ndef potencia(a, b):\n    return a ** b\n\ndef raiz_cuadrada(a):\n    if a < 0:\n        return \"Error: no se puede raiz de negativo\"\n    return a ** 0.5\n```\n\n## Menu interactivo\n```python\ndef mostrar_menu():\n    print(\"\\n=== CALCULADORA ===\")\n    print(\"1. Sumar\")\n    print(\"2. Restar\")\n    print(\"3. Multiplicar\")\n    print(\"4. Dividir\")\n    print(\"5. Potencia\")\n    print(\"6. Raiz cuadrada\")\n    print(\"0. Salir\")\n\ndef obtener_numero(mensaje):\n    while True:\n        try:\n            return float(input(mensaje))\n        except ValueError:\n            print(\"Ingresa un numero valido\")\n```\n\n## Bucle principal\n```python\ndef main():\n    historial = []\n    while True:\n        mostrar_menu()\n        opcion = input(\"Elige opcion: \")\n        if opcion == \"0\":\n            print(\"Historial:\", historial)\n            break\n        a = obtener_numero(\"Primer numero: \")\n        if opcion != \"6\":\n            b = obtener_numero(\"Segundo numero: \")\n        # ejecutar operacion y guardar en historial\n\nmain()\n```\n\n## Conceptos aplicados\n- Funciones con parametros y return\n- Validacion de entrada con try/except\n- Bucle while para menu\n- Listas para historial\n- Condicionales para seleccion",
   quiz:[{q:"Por que separar cada operacion en su propia funcion?",a:"Es obligatorio",b:"Reutilizacion, legibilidad y facilidad de pruebas",c:"Es mas rapido",d:"Python lo requiere",correct:"b",exp:"Funciones separadas permiten reutilizar, probar y mantener el codigo facilmente."},
   {q:"Como evitar error de division por cero?",a:"Ignorarlo",b:"Validar que b != 0 antes de dividir",c:"Usar try global",d:"No permitir dividir",correct:"b",exp:"Verificar que el divisor no sea cero antes de ejecutar la operacion."},
   {q:"Para que sirve el historial en la calculadora?",a:"Decoracion",b:"Guardar todas las operaciones realizadas",c:"Acelerar calculos",d:"Validar resultados",correct:"b",exp:"El historial almacena cada operacion para que el usuario pueda revisarlas al final."},
   {q:"Que estructura de control usa el menu principal?",a:"for",b:"while True con break",c:"if solamente",d:"recursion",correct:"b",exp:"while True crea un bucle infinito que solo se detiene con break cuando el usuario elige salir."},
   {q:"Que funcion integrada convierte texto a numero decimal?",a:"int()",b:"float()",c:"str()",d:"number()",correct:"b",exp:"float() convierte un string a numero decimal (punto flotante)."}]},

  {subjectId:"0df94819-8ccc-499b-ae88-7ed70713295d",number:15,title:"Proyecto: gestor de contactos (CRUD con archivos)",video:"https://www.youtube.com/watch?v=LKGj7f_kqeQ",
   theory:"# Proyecto: Gestor de Contactos CRUD\n\nConstruiremos un gestor de contactos completo que guarda datos en archivos JSON.\n\n## CRUD\n- **C**reate: agregar contacto\n- **R**ead: ver contactos\n- **U**pdate: editar contacto\n- **D**elete: eliminar contacto\n\n## Cargar y guardar datos\n```python\nimport json\n\nARCHIVO = \"contactos.json\"\n\ndef cargar_contactos():\n    try:\n        with open(ARCHIVO, \"r\") as f:\n            return json.load(f)\n    except FileNotFoundError:\n        return []\n\ndef guardar_contactos(contactos):\n    with open(ARCHIVO, \"w\") as f:\n        json.dump(contactos, f, indent=2)\n```\n\n## Crear contacto\n```python\ndef agregar_contacto(contactos):\n    nombre = input(\"Nombre: \")\n    telefono = input(\"Telefono: \")\n    email = input(\"Email: \")\n    contacto = {\n        \"nombre\": nombre,\n        \"telefono\": telefono,\n        \"email\": email\n    }\n    contactos.append(contacto)\n    guardar_contactos(contactos)\n    print(\"Contacto agregado\")\n```\n\n## Buscar contacto\n```python\ndef buscar_contacto(contactos, nombre):\n    resultados = []\n    for c in contactos:\n        if nombre.lower() in c[\"nombre\"].lower():\n            resultados.append(c)\n    return resultados\n```\n\n## Eliminar contacto\n```python\ndef eliminar_contacto(contactos, indice):\n    if 0 <= indice < len(contactos):\n        eliminado = contactos.pop(indice)\n        guardar_contactos(contactos)\n        return eliminado\n    return None\n```\n\n## Conceptos integrados\n- Funciones, diccionarios, listas\n- Manejo de archivos JSON\n- try/except para errores\n- Busqueda con filtros\n- Persistencia de datos",
   quiz:[{q:"Que significa CRUD?",a:"Code, Run, Update, Deploy",b:"Create, Read, Update, Delete",c:"Copy, Rename, Undo, Delete",d:"Compile, Run, Upload, Debug",correct:"b",exp:"CRUD son las 4 operaciones basicas sobre datos: Crear, Leer, Actualizar, Eliminar."},
   {q:"Por que usar JSON para guardar contactos?",a:"Es el unico formato",b:"Es legible, estructurado y Python tiene soporte nativo",c:"Es mas rapido que SQL",d:"Ocupa menos espacio",correct:"b",exp:"JSON es legible para humanos, estructurado y Python lo maneja con el modulo json integrado."},
   {q:"Que hace json.dump()?",a:"Lee JSON",b:"Convierte string a dict",c:"Escribe datos Python como JSON en un archivo",d:"Imprime JSON",correct:"c",exp:"json.dump() serializa datos Python y los escribe en un archivo en formato JSON."},
   {q:"Como manejar que el archivo no exista al cargar?",a:"Ignorar",b:"try/except FileNotFoundError y retornar lista vacia",c:"Crear archivo siempre",d:"Usar base de datos",correct:"b",exp:"Si el archivo no existe, capturamos FileNotFoundError y retornamos una lista vacia como valor inicial."},
   {q:"Que hace el metodo pop() en una lista?",a:"Agrega elemento",b:"Elimina y retorna el elemento en el indice dado",c:"Busca elemento",d:"Ordena la lista",correct:"b",exp:"pop(indice) elimina el elemento en esa posicion y lo retorna para poder usarlo."}]},

  {subjectId:"0df94819-8ccc-499b-ae88-7ed70713295d",number:16,title:"Repaso final y evaluacion del modulo",video:"https://www.youtube.com/watch?v=fMGCgBBNxKY",
   theory:"# Repaso Final - Fundamentos de Programacion\n\n## Temas cubiertos en el modulo\n\n### Bloque 1: Fundamentos (S1-S4)\n- Variables y tipos de datos (int, float, str, bool)\n- Operadores aritmeticos, comparacion, logicos\n- Condicionales (if, elif, else)\n- Bucles (for, while, break, continue)\n- Entrada/salida (input, print)\n\n### Bloque 2: Estructuras de datos (S5-S8)\n- Funciones (def, parametros, return, lambda)\n- Listas y tuplas (mutables vs inmutables)\n- Diccionarios y conjuntos\n- Strings y formateo\n\n### Bloque 3: Programacion intermedia (S9-S13)\n- Archivos (open, read, write, with)\n- Errores (try, except, finally, raise)\n- Modulos y paquetes (import, pip, venv)\n- POO: clases, objetos, atributos, metodos\n- Herencia y polimorfismo\n\n### Bloque 4: Proyectos (S14-S15)\n- Calculadora con funciones\n- Gestor de contactos CRUD\n\n## Tips para la evaluacion\n1. Practica escribiendo codigo, no solo leyendo\n2. Entiende la diferencia entre listas, tuplas, dicts y sets\n3. Domina funciones: parametros, return, scope\n4. POO: clases, herencia, polimorfismo\n5. Siempre maneja errores con try/except\n6. Usa with para archivos\n\n## Que sigue despues\n- Semestre 2: Algoritmos y Estructuras de Datos\n- Semestre 2: Bases de Datos con SQL\n- Semestre 2: Matematicas para IA\n\nHas completado los fundamentos de Python. Ahora tienes las bases para construir cualquier proyecto.",
   quiz:[{q:"Cual es la diferencia principal entre lista y tupla?",a:"Tupla es mas larga",b:"Lista es mutable, tupla es inmutable",c:"No hay diferencia",d:"Tupla usa corchetes",correct:"b",exp:"Las listas se pueden modificar despues de crearlas; las tuplas no."},
   {q:"Que bloque se ejecuta siempre en try/except/finally?",a:"try",b:"except",c:"finally",d:"else",correct:"c",exp:"finally se ejecuta siempre, haya o no error, ideal para limpieza de recursos."},
   {q:"Que retorna type(3.14)?",a:"int",b:"float",c:"str",d:"number",correct:"b",exp:"3.14 es un numero con punto decimal, por lo tanto su tipo es float."},
   {q:"Para que sirve super() en una clase hija?",a:"Crear nueva clase",b:"Acceder a metodos de la clase padre",c:"Eliminar herencia",d:"Crear objeto",correct:"b",exp:"super() permite llamar metodos de la clase padre desde la clase hija."},
   {q:"Que patron de diseno usa el gestor de contactos?",a:"MVC",b:"CRUD",c:"Singleton",d:"Factory",correct:"b",exp:"CRUD (Create, Read, Update, Delete) es el patron de las 4 operaciones basicas sobre datos."}]},

  // =============================================
  // CD - Introduccion a Ciencia de Datos (sesiones 9-16)
  // =============================================
  {subjectId:"015311e7-c0d0-4065-abbf-83ab210da384",number:9,title:"Pandas avanzado: groupby y agregaciones",video:"https://www.youtube.com/watch?v=txMdrV1Ut64",
   theory:"# GroupBy y Agregaciones en Pandas\n\nGroupBy es una de las operaciones mas poderosas de Pandas: dividir datos, aplicar funcion y combinar resultados.\n\n## Concepto Split-Apply-Combine\n1. **Split**: dividir datos por grupos\n2. **Apply**: aplicar funcion a cada grupo\n3. **Combine**: combinar resultados\n\n## groupby basico\n```python\nimport pandas as pd\n\ndf = pd.DataFrame({\n    \"ciudad\": [\"Quito\",\"Guayaquil\",\"Quito\",\"Guayaquil\",\"Cuenca\"],\n    \"ventas\": [100, 200, 150, 300, 80],\n    \"categoria\": [\"A\",\"B\",\"A\",\"A\",\"B\"]\n})\n\n# Ventas promedio por ciudad\ndf.groupby(\"ciudad\")[\"ventas\"].mean()\n```\n\n## Multiples agregaciones\n```python\ndf.groupby(\"ciudad\")[\"ventas\"].agg([\"mean\",\"sum\",\"count\",\"max\"])\n```\n\n## Agrupar por multiples columnas\n```python\ndf.groupby([\"ciudad\",\"categoria\"])[\"ventas\"].sum()\n```\n\n## agg() con funciones personalizadas\n```python\ndf.groupby(\"ciudad\").agg(\n    total_ventas=(\"ventas\", \"sum\"),\n    promedio_ventas=(\"ventas\", \"mean\"),\n    num_registros=(\"ventas\", \"count\")\n)\n```\n\n## transform()\nRetorna resultado con el mismo tamano del DataFrame original:\n```python\ndf[\"media_ciudad\"] = df.groupby(\"ciudad\")[\"ventas\"].transform(\"mean\")\n```\n\n## filter()\nFiltra grupos completos:\n```python\ndf.groupby(\"ciudad\").filter(lambda x: x[\"ventas\"].mean() > 100)\n```",
   quiz:[{q:"Que patron sigue groupby?",a:"Map-Reduce",b:"Split-Apply-Combine",c:"Extract-Transform-Load",d:"Filter-Sort-Group",correct:"b",exp:"GroupBy divide los datos, aplica una funcion a cada grupo y combina los resultados."},
   {q:"Que hace .agg(['mean','sum'])?",a:"Solo mean",b:"Solo sum",c:"Aplica ambas funciones al grupo",d:"Error",correct:"c",exp:"agg() puede aplicar multiples funciones de agregacion simultaneamente."},
   {q:"Diferencia entre agg() y transform()?",a:"Son iguales",b:"agg reduce filas, transform mantiene el tamano original",c:"transform reduce filas",d:"agg es mas rapido",correct:"b",exp:"agg reduce a una fila por grupo; transform retorna un resultado del mismo tamano que el original."},
   {q:"Para agrupar por 2 columnas se usa:",a:"groupby(col1, col2)",b:"groupby([col1, col2])",c:"groupby(col1).groupby(col2)",d:"group(col1, col2)",correct:"b",exp:"Se pasa una lista de columnas dentro de groupby para agrupar por multiples criterios."},
   {q:"filter() en groupby filtra:",a:"Filas individuales",b:"Columnas",c:"Grupos completos segun condicion",d:"Valores nulos",correct:"c",exp:"filter() evalua la condicion sobre cada grupo completo y descarta los que no cumplen."}]},

  {subjectId:"015311e7-c0d0-4065-abbf-83ab210da384",number:10,title:"Merge, join y concatenacion de DataFrames",video:"https://www.youtube.com/watch?v=iYWKfUOtGaw",
   theory:"# Merge, Join y Concatenacion\n\nCombinar DataFrames es esencial cuando los datos vienen de multiples fuentes.\n\n## pd.concat() - Concatenar\nApila DataFrames vertical u horizontalmente:\n```python\nimport pandas as pd\n\ndf1 = pd.DataFrame({\"nombre\": [\"Ana\",\"Luis\"], \"edad\": [25,30]})\ndf2 = pd.DataFrame({\"nombre\": [\"Carlos\"], \"edad\": [28]})\n\n# Vertical (apilar filas)\nresultado = pd.concat([df1, df2], ignore_index=True)\n```\n\n## pd.merge() - Similar a SQL JOIN\n```python\nclientes = pd.DataFrame({\n    \"id\": [1,2,3],\n    \"nombre\": [\"Ana\",\"Luis\",\"Maria\"]\n})\ncompras = pd.DataFrame({\n    \"cliente_id\": [1,1,2],\n    \"producto\": [\"Laptop\",\"Mouse\",\"Teclado\"]\n})\n\n# Inner join\nresultado = pd.merge(clientes, compras, left_on=\"id\", right_on=\"cliente_id\")\n```\n\n## Tipos de merge\n- `inner`: solo coincidencias (por defecto)\n- `left`: todas las filas de la izquierda\n- `right`: todas las filas de la derecha\n- `outer`: todas las filas de ambos\n\n```python\npd.merge(clientes, compras, left_on=\"id\", right_on=\"cliente_id\", how=\"left\")\n```\n\n## .join() - Por indice\n```python\ndf1.set_index(\"id\").join(df2.set_index(\"cliente_id\"), how=\"inner\")\n```\n\n## merge en columnas con mismo nombre\n```python\npd.merge(df1, df2, on=\"nombre\")  # columna compartida\n```\n\n## Merge con indicador\n```python\npd.merge(df1, df2, on=\"id\", how=\"outer\", indicator=True)\n# Agrega columna _merge: left_only, right_only, both\n```",
   quiz:[{q:"Cual es la diferencia entre concat y merge?",a:"Son lo mismo",b:"concat apila, merge combina por columna clave",c:"merge apila, concat combina",d:"concat es mas rapido",correct:"b",exp:"concat apila DataFrames; merge los combina usando una columna clave como en SQL JOIN."},
   {q:"Que tipo de merge solo incluye coincidencias?",a:"outer",b:"left",c:"inner",d:"right",correct:"c",exp:"inner join solo retorna filas donde hay coincidencia en ambos DataFrames."},
   {q:"pd.merge(df1, df2, how='left') retorna:",a:"Solo coincidencias",b:"Todas las filas de df1 + coincidencias de df2",c:"Todas las filas de df2",d:"Todas las filas de ambos",correct:"b",exp:"Left join mantiene todas las filas del DataFrame izquierdo y agrega datos del derecho donde coincida."},
   {q:"Parametro para ignorar indices al concatenar?",a:"reset=True",b:"ignore_index=True",c:"no_index=True",d:"clean_index=True",correct:"b",exp:"ignore_index=True crea un nuevo indice secuencial en el resultado."},
   {q:"indicator=True en merge agrega columna:",a:"_source",b:"_merge",c:"_join",d:"_origin",correct:"b",exp:"Agrega columna _merge con valores left_only, right_only o both."}]},

  {subjectId:"015311e7-c0d0-4065-abbf-83ab210da384",number:11,title:"Series temporales basicas",video:"https://www.youtube.com/watch?v=r0Yrjx4db3k",
   theory:"# Series Temporales con Pandas\n\nUna serie temporal es una secuencia de datos ordenados en el tiempo. Pandas tiene herramientas poderosas para trabajar con fechas.\n\n## Crear fechas\n```python\nimport pandas as pd\n\n# Rango de fechas\nfechas = pd.date_range(start=\"2026-01-01\", periods=30, freq=\"D\")\n\n# Convertir columna a datetime\ndf[\"fecha\"] = pd.to_datetime(df[\"fecha\"])\n```\n\n## DatetimeIndex\n```python\ndf = df.set_index(\"fecha\")\n\n# Seleccionar por fecha\ndf[\"2026-01\"]          # todo enero\ndf[\"2026-01-15\":]      # desde 15 enero\n```\n\n## Resampleo (resample)\nCambiar la frecuencia de los datos:\n```python\n# Datos diarios a semanales\ndf.resample(\"W\").mean()\n\n# Datos diarios a mensuales\ndf.resample(\"M\").sum()\n```\n\n## Media movil (rolling)\n```python\n# Media movil de 7 dias\ndf[\"media_7d\"] = df[\"ventas\"].rolling(window=7).mean()\n```\n\n## Shift\nDesplazar datos en el tiempo:\n```python\ndf[\"ventas_ayer\"] = df[\"ventas\"].shift(1)\ndf[\"cambio\"] = df[\"ventas\"] - df[\"ventas\"].shift(1)\n```\n\n## Extraer componentes\n```python\ndf[\"anio\"] = df.index.year\ndf[\"mes\"] = df.index.month\ndf[\"dia_semana\"] = df.index.dayofweek\n```\n\n## Frecuencias comunes\n- D: diario, W: semanal, M: mensual\n- H: hora, T: minuto, Q: trimestral, A: anual",
   quiz:[{q:"Que es una serie temporal?",a:"Datos sin orden",b:"Datos ordenados en el tiempo",c:"Un tipo de grafico",d:"Una base de datos",correct:"b",exp:"Una serie temporal es una secuencia de datos indexados por tiempo."},
   {q:"Que hace resample('M').sum()?",a:"Filtra por mes",b:"Agrupa datos por mes y suma cada grupo",c:"Cuenta meses",d:"Ordena por mes",correct:"b",exp:"resample cambia la frecuencia (a mensual) y sum() agrega los valores de cada mes."},
   {q:"rolling(window=7).mean() calcula:",a:"Media de todo",b:"Media movil de 7 periodos",c:"7 medias",d:"Mediana de 7 valores",correct:"b",exp:"rolling(7) crea una ventana deslizante de 7 periodos y mean() calcula la media de cada ventana."},
   {q:"shift(1) hace:",a:"Elimina primera fila",b:"Desplaza datos una posicion hacia abajo",c:"Suma 1 a todos los valores",d:"Ordena datos",correct:"b",exp:"shift(1) mueve los datos una fila hacia abajo, util para comparar con el periodo anterior."},
   {q:"Como convertir una columna de texto a fecha?",a:"str_to_date()",b:"pd.to_datetime()",c:"datetime.parse()",d:"convert_date()",correct:"b",exp:"pd.to_datetime() convierte strings a objetos datetime de Pandas."}]},

  {subjectId:"015311e7-c0d0-4065-abbf-83ab210da384",number:12,title:"Introduccion a Scikit-learn",video:"https://www.youtube.com/watch?v=J5bV50Olx9A",
   theory:"# Introduccion a Scikit-learn\n\nScikit-learn (sklearn) es la libreria mas popular de Machine Learning en Python. Provee herramientas para clasificacion, regresion, clustering y preprocesamiento.\n\n## Instalacion\n```python\npip install scikit-learn\nimport sklearn\n```\n\n## Flujo de trabajo ML\n1. Cargar datos\n2. Dividir en train/test\n3. Elegir modelo\n4. Entrenar (fit)\n5. Predecir (predict)\n6. Evaluar\n\n## Train/Test Split\n```python\nfrom sklearn.model_selection import train_test_split\n\nX = df[[\"edad\", \"salario\"]]  # features\ny = df[\"compra\"]              # target\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n```\n\n## Entrenar un modelo\n```python\nfrom sklearn.linear_model import LinearRegression\n\nmodelo = LinearRegression()\nmodelo.fit(X_train, y_train)\n```\n\n## Predecir y evaluar\n```python\npredicciones = modelo.predict(X_test)\n\nfrom sklearn.metrics import mean_squared_error, r2_score\nprint(\"MSE:\", mean_squared_error(y_test, predicciones))\nprint(\"R2:\", r2_score(y_test, predicciones))\n```\n\n## Algoritmos populares\n- LinearRegression: regresion lineal\n- LogisticRegression: clasificacion binaria\n- DecisionTreeClassifier: arbol de decision\n- RandomForestClassifier: bosque aleatorio\n- KNeighborsClassifier: K vecinos\n\n## Preprocesamiento\n```python\nfrom sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)\n```",
   quiz:[{q:"Cual es el flujo basico de ML con sklearn?",a:"Importar y predecir",b:"Cargar, dividir, entrenar, predecir, evaluar",c:"Solo entrenar",d:"Graficar y analizar",correct:"b",exp:"El flujo completo incluye: cargar datos, split train/test, entrenar modelo, predecir y evaluar."},
   {q:"test_size=0.2 significa:",a:"20% para entrenamiento",b:"20% para prueba, 80% para entrenamiento",c:"2 filas para test",d:"20 registros",correct:"b",exp:"test_size=0.2 reserva el 20% de los datos para evaluacion y usa el 80% para entrenar."},
   {q:"Que metodo entrena el modelo?",a:"train()",b:"learn()",c:"fit()",d:"predict()",correct:"c",exp:"fit() entrena el modelo ajustando sus parametros a los datos de entrenamiento."},
   {q:"R2 score cercano a 1 indica:",a:"Modelo malo",b:"Modelo predice bien",c:"Error alto",d:"Sobreajuste siempre",correct:"b",exp:"R2 cercano a 1 indica que el modelo explica bien la variabilidad de los datos."},
   {q:"Para que sirve StandardScaler?",a:"Entrenar modelo",b:"Normalizar features a media 0 y std 1",c:"Dividir datos",d:"Visualizar",correct:"b",exp:"StandardScaler transforma los datos para que tengan media 0 y desviacion estandar 1."}]},

  {subjectId:"015311e7-c0d0-4065-abbf-83ab210da384",number:13,title:"Regresion lineal simple",video:"https://www.youtube.com/watch?v=w2RJ1D6kz-o",
   theory:"# Regresion Lineal Simple\n\nLa regresion lineal modela la relacion entre una variable independiente (X) y una dependiente (y) con una linea recta.\n\n## Ecuacion\n```\ny = mx + b\n```\n- m: pendiente (slope)\n- b: intercepto (donde cruza el eje Y)\n\n## Ejemplo completo\n```python\nimport pandas as pd\nimport numpy as np\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import train_test_split\nimport matplotlib.pyplot as plt\n\n# Datos: horas de estudio vs calificacion\ndata = {\n    \"horas\": [1,2,3,4,5,6,7,8,9,10],\n    \"nota\": [2,4,5,4,5,7,8,9,10,10]\n}\ndf = pd.DataFrame(data)\n\n# Preparar datos\nX = df[[\"horas\"]]\ny = df[\"nota\"]\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# Entrenar modelo\nmodelo = LinearRegression()\nmodelo.fit(X_train, y_train)\n\nprint(\"Pendiente:\", modelo.coef_[0])\nprint(\"Intercepto:\", modelo.intercept_)\n```\n\n## Visualizar la regresion\n```python\nplt.scatter(X, y, color=\"blue\", label=\"Datos reales\")\nplt.plot(X, modelo.predict(X), color=\"red\", label=\"Regresion\")\nplt.xlabel(\"Horas de estudio\")\nplt.ylabel(\"Calificacion\")\nplt.legend()\nplt.show()\n```\n\n## Metricas de evaluacion\n- **MSE** (Mean Squared Error): error cuadratico medio\n- **RMSE**: raiz de MSE (en mismas unidades que y)\n- **R2**: porcentaje de varianza explicada (0 a 1)\n- **MAE**: error absoluto medio\n\n## Cuando usar regresion lineal\n- Relacion lineal entre variables\n- Variable target continua\n- Pocos outliers extremos",
   quiz:[{q:"Que modela la regresion lineal simple?",a:"Relacion entre 3 variables",b:"Relacion lineal entre X e y con una recta",c:"Clasificacion binaria",d:"Agrupamiento de datos",correct:"b",exp:"La regresion lineal simple modela la relacion entre una variable independiente y una dependiente con una linea."},
   {q:"En y = mx + b, que representa m?",a:"Intercepto",b:"Error",c:"Pendiente de la recta",d:"Constante",correct:"c",exp:"m es la pendiente: cuanto cambia y por cada unidad de cambio en x."},
   {q:"RMSE es preferible a MSE porque:",a:"Es mas grande",b:"Esta en las mismas unidades que la variable objetivo",c:"Es siempre menor",d:"Es mas preciso",correct:"b",exp:"RMSE es la raiz de MSE, lo que lo pone en las mismas unidades que y, facilitando la interpretacion."},
   {q:"R2 = 0.85 significa:",a:"85% de error",b:"El modelo explica 85% de la variabilidad de los datos",c:"85 predicciones correctas",d:"Error de 15 unidades",correct:"b",exp:"R2 indica el porcentaje de varianza de y que es explicada por el modelo."},
   {q:"Cuando NO usar regresion lineal?",a:"Con datos numericos",b:"Con relacion lineal",c:"Cuando la relacion entre variables no es lineal",d:"Con pocas variables",correct:"c",exp:"Si la relacion es curva o no lineal, la regresion lineal dara malos resultados."}]},

  {subjectId:"015311e7-c0d0-4065-abbf-83ab210da384",number:14,title:"Proyecto: analisis de dataset publico (Kaggle)",video:"https://www.youtube.com/watch?v=GPVsHOlRBBI",
   theory:"# Proyecto: Analisis de Dataset de Kaggle\n\nEn este proyecto realizaremos un analisis completo de un dataset real de Kaggle siguiendo el proceso profesional de ciencia de datos.\n\n## Paso 1: Obtener datos\n```python\nimport pandas as pd\n\n# Ejemplo: dataset Titanic de Kaggle\ndf = pd.read_csv(\"titanic.csv\")\nprint(\"Shape:\", df.shape)\nprint(df.head())\n```\n\n## Paso 2: Exploracion inicial\n```python\ndf.info()             # tipos y nulos\ndf.describe()         # estadisticas\ndf.isnull().sum()     # conteo de nulos por columna\ndf.duplicated().sum() # filas duplicadas\n```\n\n## Paso 3: Limpieza\n```python\n# Rellenar nulos\ndf[\"edad\"] = df[\"edad\"].fillna(df[\"edad\"].median())\n\n# Eliminar columnas irrelevantes\ndf = df.drop(columns=[\"cabin\", \"ticket\"])\n\n# Convertir categoricas\ndf[\"sexo_num\"] = df[\"sexo\"].map({\"male\": 0, \"female\": 1})\n```\n\n## Paso 4: Analisis exploratorio\n```python\nimport matplotlib.pyplot as plt\n\n# Distribucion de supervivencia\ndf[\"survived\"].value_counts().plot(kind=\"bar\")\nplt.title(\"Supervivencia en el Titanic\")\nplt.show()\n\n# Supervivencia por clase\ndf.groupby(\"pclass\")[\"survived\"].mean().plot(kind=\"bar\")\n```\n\n## Paso 5: Insights\n```python\n# Correlaciones\nprint(df.corr()[\"survived\"].sort_values(ascending=False))\n```\n\n## Paso 6: Reporte\nDocumentar hallazgos principales:\n- Tasa de supervivencia general\n- Factores mas importantes\n- Visualizaciones clave\n- Conclusiones y recomendaciones",
   quiz:[{q:"Cual es el primer paso al recibir un dataset nuevo?",a:"Entrenar modelo",b:"Explorar estructura: shape, info(), head()",c:"Eliminar columnas",d:"Crear graficos",correct:"b",exp:"Siempre explorar primero para entender la estructura, tipos y dimension de los datos."},
   {q:"Por que usar mediana para rellenar nulos en edad?",a:"Es mas facil",b:"La mediana es robusta a outliers",c:"Es siempre mejor que media",d:"Kaggle lo requiere",correct:"b",exp:"La mediana no se ve afectada por valores extremos, lo que la hace mejor que la media para datos con outliers."},
   {q:"Que hace df.corr()?",a:"Cuenta registros",b:"Calcula la correlacion entre todas las columnas numericas",c:"Corrige errores",d:"Ordena datos",correct:"b",exp:"corr() genera una matriz de correlacion que muestra la relacion lineal entre variables numericas."},
   {q:"En un analisis de Kaggle, que va despues de la limpieza?",a:"Subir resultados",b:"Analisis exploratorio y visualizacion",c:"Mas limpieza",d:"Entrenar modelo inmediatamente",correct:"b",exp:"Despues de limpiar se hace EDA: visualizaciones y analisis para descubrir patrones."},
   {q:"value_counts() es util para:",a:"Calcular media",b:"Ver la frecuencia de cada valor unico en una columna",c:"Ordenar datos",d:"Eliminar duplicados",correct:"b",exp:"value_counts() cuenta cuantas veces aparece cada valor unico, ideal para variables categoricas."}]},

  {subjectId:"015311e7-c0d0-4065-abbf-83ab210da384",number:15,title:"Proyecto: dashboard de datos con Streamlit",video:"https://www.youtube.com/watch?v=Sb0A9i6d320",
   theory:"# Proyecto: Dashboard con Streamlit\n\nStreamlit permite crear aplicaciones web interactivas para datos usando solo Python.\n\n## Instalacion\n```bash\npip install streamlit\n```\n\n## App basica (app.py)\n```python\nimport streamlit as st\nimport pandas as pd\n\nst.title(\"Mi Dashboard de Datos\")\nst.write(\"Bienvenido al analisis interactivo\")\n\n# Cargar datos\ndf = pd.read_csv(\"datos.csv\")\nst.dataframe(df.head())\n```\n\n## Ejecutar\n```bash\nstreamlit run app.py\n```\n\n## Widgets interactivos\n```python\n# Selector\ncolumna = st.selectbox(\"Elige columna\", df.columns)\n\n# Slider\nminimo = st.slider(\"Valor minimo\", 0, 100, 50)\n\n# Filtro\ndf_filtrado = df[df[columna] >= minimo]\nst.write(\"Registros:\", len(df_filtrado))\n```\n\n## Graficos\n```python\nimport matplotlib.pyplot as plt\n\nfig, ax = plt.subplots()\nax.hist(df[columna], bins=20)\nax.set_title(\"Distribucion de \" + columna)\nst.pyplot(fig)\n\n# Graficos nativos de Streamlit\nst.line_chart(df[[\"fecha\", \"ventas\"]].set_index(\"fecha\"))\nst.bar_chart(df[\"categoria\"].value_counts())\n```\n\n## Layout\n```python\ncol1, col2 = st.columns(2)\nwith col1:\n    st.metric(\"Total Ventas\", \"$12,500\", \"+15%\")\nwith col2:\n    st.metric(\"Clientes\", \"342\", \"-5%\")\n\n# Sidebar\nwith st.sidebar:\n    st.header(\"Filtros\")\n    fecha = st.date_input(\"Desde\")\n```\n\n## Ventajas de Streamlit\n- Solo Python, sin HTML/CSS/JS\n- Reactivo automaticamente\n- Deploy gratuito en Streamlit Cloud\n- Ideal para prototipos y dashboards internos",
   quiz:[{q:"Que es Streamlit?",a:"Base de datos",b:"Framework para crear apps web de datos con Python",c:"Libreria de graficos",d:"Editor de codigo",correct:"b",exp:"Streamlit convierte scripts Python en apps web interactivas sin necesidad de HTML/CSS/JS."},
   {q:"Como se ejecuta una app de Streamlit?",a:"python app.py",b:"streamlit run app.py",c:"flask run",d:"npm start",correct:"b",exp:"El comando streamlit run app.py inicia el servidor y abre la app en el navegador."},
   {q:"st.selectbox() crea:",a:"Un grafico",b:"Un selector desplegable interactivo",c:"Una tabla",d:"Un boton",correct:"b",exp:"selectbox crea un dropdown donde el usuario puede elegir entre opciones."},
   {q:"st.metric() muestra:",a:"Solo un numero",b:"Un valor con titulo y cambio porcentual",c:"Un grafico de metricas",d:"Una tabla de datos",correct:"b",exp:"metric muestra un KPI con titulo, valor principal y delta (cambio)."},
   {q:"Ventaja principal de Streamlit sobre Flask para dashboards?",a:"Mas rapido",b:"No necesitas HTML/CSS, solo Python",c:"Mejor para APIs",d:"Gratis siempre",correct:"b",exp:"Streamlit elimina la necesidad de escribir frontend, ideal para cientificos de datos que solo saben Python."}]},

  {subjectId:"015311e7-c0d0-4065-abbf-83ab210da384",number:16,title:"Repaso final y evaluacion del modulo",video:"https://www.youtube.com/watch?v=vmEHCJofslg",
   theory:"# Repaso Final - Introduccion a Ciencia de Datos\n\n## Temas cubiertos\n\n### Bloque 1: Fundamentos (S1-S4)\n- Que es ciencia de datos y su ecosistema\n- NumPy: arrays, operaciones vectorizadas\n- Pandas: Series, DataFrames, indexacion\n- Carga de datos: CSV, Excel, JSON, SQL\n\n### Bloque 2: Limpieza y analisis (S5-S8)\n- Limpieza: nulos, duplicados, tipos\n- Estadistica descriptiva: media, mediana, std, correlacion\n- Matplotlib: line, bar, hist, scatter, subplots\n- EDA: proceso completo de exploracion\n\n### Bloque 3: Tecnicas avanzadas (S9-S13)\n- Pandas avanzado: groupby, agg, transform\n- Merge, join y concat de DataFrames\n- Series temporales: resample, rolling, shift\n- Scikit-learn: flujo ML, train/test split\n- Regresion lineal: pendiente, intercepto, R2\n\n### Bloque 4: Proyectos (S14-S15)\n- Analisis completo de dataset Kaggle\n- Dashboard interactivo con Streamlit\n\n## Herramientas dominadas\n- Python, NumPy, Pandas, Matplotlib, Scikit-learn, Streamlit\n\n## Tips para la evaluacion\n1. Domina el flujo: cargar, limpiar, explorar, modelar, comunicar\n2. Practica con datasets reales de Kaggle\n3. Sabe explicar cuando usar cada tipo de grafico\n4. Entiende regresion lineal y sus metricas\n5. Sabe combinar DataFrames con merge y concat\n\n## Que sigue\n- Semestre 2: Machine Learning supervisado y no supervisado\n- Semestre 2: Estadistica inferencial\n- Semestre 2: SQL avanzado para analisis",
   quiz:[{q:"Cuantas fases tiene el proceso de ciencia de datos?",a:"3",b:"5",c:"Obtener, limpiar, explorar, modelar, comunicar = 5",d:"7",correct:"c",exp:"Las 5 fases son: obtener datos, limpiar, explorar (EDA), modelar y comunicar resultados."},
   {q:"Que libreria usamos para Machine Learning?",a:"Pandas",b:"Matplotlib",c:"Scikit-learn",d:"NumPy",correct:"c",exp:"Scikit-learn es la libreria principal para algoritmos de Machine Learning en Python."},
   {q:"groupby().agg() es util para:",a:"Limpiar datos",b:"Calcular estadisticas por grupo",c:"Crear graficos",d:"Entrenar modelos",correct:"b",exp:"groupby().agg() permite calcular multiples estadisticas para cada grupo de datos."},
   {q:"Que herramienta creamos para visualizacion interactiva?",a:"Jupyter",b:"Matplotlib",c:"Dashboard con Streamlit",d:"Excel",correct:"c",exp:"Streamlit permite crear dashboards web interactivos usando solo Python."},
   {q:"R2 = 0 en regresion lineal significa:",a:"Modelo perfecto",b:"El modelo no explica nada de la variabilidad",c:"Error minimo",d:"No hay datos",correct:"b",exp:"R2 = 0 indica que el modelo no captura ninguna relacion entre las variables."}]},

  // =============================================
  // BD - Introduccion a Big Data (sesiones 9-16)
  // =============================================
  {subjectId:"191281b2-a3bb-4fbd-9a1d-f92443d1be3b",number:9,title:"Introduccion a Python para Big Data: PySpark",video:"https://www.youtube.com/watch?v=_C8kWso4ne4",
   theory:"# Python para Big Data: PySpark\n\nPySpark es la interfaz Python de Apache Spark, el motor de procesamiento distribuido mas popular.\n\n## Instalacion\n```bash\npip install pyspark\n```\n\n## Iniciar sesion Spark\n```python\nfrom pyspark.sql import SparkSession\n\nspark = SparkSession.builder \\\n    .appName(\"MiApp\") \\\n    .master(\"local[*]\") \\\n    .getOrCreate()\n```\n\n## Crear DataFrames\n```python\n# Desde lista\ndata = [(\"Ana\", 25), (\"Luis\", 30), (\"Maria\", 28)]\ndf = spark.createDataFrame(data, [\"nombre\", \"edad\"])\ndf.show()\n```\n\n## Leer archivos\n```python\n# CSV\ndf = spark.read.csv(\"datos.csv\", header=True, inferSchema=True)\n\n# JSON\ndf = spark.read.json(\"datos.json\")\n\n# Parquet (formato optimizado)\ndf = spark.read.parquet(\"datos.parquet\")\n```\n\n## Operaciones basicas\n```python\n# Seleccionar columnas\ndf.select(\"nombre\", \"edad\").show()\n\n# Filtrar\ndf.filter(df.edad > 25).show()\n\n# Agrupar\ndf.groupBy(\"ciudad\").count().show()\n\n# Ordenar\ndf.orderBy(df.edad.desc()).show()\n```\n\n## Spark SQL\n```python\ndf.createOrReplaceTempView(\"personas\")\nresultado = spark.sql(\"SELECT nombre, edad FROM personas WHERE edad > 25\")\nresultado.show()\n```\n\n## Diferencias con Pandas\n- PySpark: distribuido, millones/billones de filas\n- Pandas: en memoria, miles/millones de filas\n- PySpark usa evaluacion perezosa (lazy)\n- PySpark: show() en lugar de head()",
   quiz:[{q:"Que es PySpark?",a:"Version rapida de Pandas",b:"Interfaz Python de Apache Spark para procesamiento distribuido",c:"Base de datos",d:"Servicio en la nube",correct:"b",exp:"PySpark permite usar Spark desde Python para procesar grandes volumenes de datos."},
   {q:"Que hace SparkSession.builder.getOrCreate()?",a:"Crea base de datos",b:"Crea o reutiliza una sesion de Spark",c:"Instala Spark",d:"Conecta a servidor",correct:"b",exp:"Crea una nueva sesion de Spark o reutiliza una existente si ya fue creada."},
   {q:"Que formato es mas eficiente para Big Data?",a:"CSV",b:"JSON",c:"Parquet",d:"TXT",correct:"c",exp:"Parquet es columnar y comprimido, mucho mas eficiente para lectura y almacenamiento de Big Data."},
   {q:"Que significa evaluacion perezosa (lazy) en Spark?",a:"Es lento",b:"No ejecuta operaciones hasta que se necesita el resultado",c:"Solo funciona de noche",d:"Procesa datos incompletos",correct:"b",exp:"Las transformaciones se acumulan y solo se ejecutan cuando se llama una accion como show() o count()."},
   {q:"Principal ventaja de PySpark sobre Pandas?",a:"Sintaxis mas facil",b:"Procesa datos distribuidos en cluster de computadoras",c:"Tiene mas funciones",d:"Es gratis",correct:"b",exp:"PySpark puede distribuir el procesamiento en multiples maquinas para manejar datos masivos."}]},

  {subjectId:"191281b2-a3bb-4fbd-9a1d-f92443d1be3b",number:10,title:"Consultas SQL avanzadas para Big Data",video:"https://www.youtube.com/watch?v=7S_tz1z_5bA",
   theory:"# SQL Avanzado para Big Data\n\nSQL sigue siendo el lenguaje principal para consultar datos a gran escala. Las mismas consultas funcionan en BigQuery, Spark SQL, Hive, Presto y otros motores Big Data.\n\n## Subconsultas\n```sql\nSELECT nombre, salario\nFROM empleados\nWHERE salario > (SELECT AVG(salario) FROM empleados);\n```\n\n## Common Table Expressions (CTE)\n```sql\nWITH ventas_mensuales AS (\n    SELECT\n        EXTRACT(MONTH FROM fecha) AS mes,\n        SUM(total) AS total_ventas\n    FROM ventas\n    GROUP BY mes\n)\nSELECT mes, total_ventas\nFROM ventas_mensuales\nWHERE total_ventas > 10000;\n```\n\n## Window Functions\n```sql\nSELECT\n    nombre,\n    departamento,\n    salario,\n    ROW_NUMBER() OVER (PARTITION BY departamento ORDER BY salario DESC) AS ranking,\n    AVG(salario) OVER (PARTITION BY departamento) AS promedio_dept\nFROM empleados;\n```\n\n## Funciones de ventana comunes\n- ROW_NUMBER(): numero de fila\n- RANK(): ranking con empates\n- LAG(col, n): valor n filas atras\n- LEAD(col, n): valor n filas adelante\n- SUM() OVER(): suma acumulativa\n\n## Optimizacion para Big Data\n- Usar PARTITION BY en lugar de GROUP BY cuando sea posible\n- Filtrar temprano con WHERE\n- Evitar SELECT * en tablas grandes\n- Usar formatos columnares (Parquet, ORC)\n- Particionar tablas por fecha o region",
   quiz:[{q:"Que es un CTE en SQL?",a:"Un tipo de tabla",b:"Una subconsulta con nombre reutilizable (WITH...AS)",c:"Un comando de creacion",d:"Un tipo de indice",correct:"b",exp:"CTE (Common Table Expression) es una subconsulta temporal con nombre definida con WITH...AS."},
   {q:"Que hace ROW_NUMBER() OVER(PARTITION BY dept ORDER BY salario DESC)?",a:"Cuenta empleados",b:"Numera filas dentro de cada departamento ordenadas por salario",c:"Suma salarios",d:"Filtra departamentos",correct:"b",exp:"Asigna un numero secuencial a cada fila dentro de cada particion (departamento)."},
   {q:"Diferencia entre RANK() y ROW_NUMBER()?",a:"Son identicos",b:"RANK permite empates, ROW_NUMBER siempre es unico",c:"ROW_NUMBER permite empates",d:"RANK es mas rapido",correct:"b",exp:"RANK da el mismo numero a empates (1,1,3); ROW_NUMBER siempre asigna numeros unicos (1,2,3)."},
   {q:"Para optimizar consultas Big Data se debe:",a:"Usar SELECT * siempre",b:"Filtrar temprano y seleccionar solo columnas necesarias",c:"Evitar indices",d:"No usar WHERE",correct:"b",exp:"Filtrar pronto reduce la cantidad de datos procesados, mejorando rendimiento significativamente."},
   {q:"LAG(ventas, 1) retorna:",a:"Ventas siguiente",b:"El valor de ventas de la fila anterior",c:"Primera venta",d:"Ultima venta",correct:"b",exp:"LAG accede al valor de una fila anterior, util para comparar con periodos previos."}]},

  {subjectId:"191281b2-a3bb-4fbd-9a1d-f92443d1be3b",number:11,title:"ETL: Extract, Transform, Load",video:"https://www.youtube.com/watch?v=OW5OgsLpDCQ",
   theory:"# ETL: Extract, Transform, Load\n\nETL es el proceso fundamental de mover datos desde sus fuentes originales hasta un sistema de analisis.\n\n## Las 3 fases\n\n### 1. Extract (Extraer)\nObtener datos de multiples fuentes:\n- Bases de datos (MySQL, PostgreSQL)\n- APIs (REST, GraphQL)\n- Archivos (CSV, JSON, Excel)\n- Logs de servidores\n- Streaming (Kafka, webhooks)\n\n### 2. Transform (Transformar)\nLimpiar y preparar datos:\n```python\n# Ejemplo con PySpark\nfrom pyspark.sql.functions import col, when, lower, trim\n\ndf_limpio = df \\\n    .withColumn(\"email\", lower(trim(col(\"email\")))) \\\n    .withColumn(\"estado\", when(col(\"activo\") == 1, \"Activo\").otherwise(\"Inactivo\")) \\\n    .dropDuplicates([\"email\"]) \\\n    .filter(col(\"email\").isNotNull())\n```\n\nTransformaciones comunes:\n- Limpieza de nulos y duplicados\n- Normalizacion de formatos\n- Calculo de campos derivados\n- Agregaciones y joins\n- Validacion de calidad\n\n### 3. Load (Cargar)\nGuardar en el destino:\n```python\n# A archivo Parquet\ndf_limpio.write.parquet(\"output/datos_limpios\")\n\n# A base de datos\ndf_limpio.write \\\n    .format(\"jdbc\") \\\n    .option(\"url\", \"jdbc:postgresql://servidor:5432/db\") \\\n    .option(\"dbtable\", \"tabla_destino\") \\\n    .save()\n```\n\n## ETL vs ELT\n- **ETL**: transforma ANTES de cargar (tradicional)\n- **ELT**: carga primero, transforma en destino (moderno, BigQuery)\n\n## Herramientas ETL populares\n- Apache Airflow (orquestacion)\n- dbt (transformacion en warehouse)\n- Spark (procesamiento distribuido)\n- AWS Glue, Google Dataflow",
   quiz:[{q:"Que significan las siglas ETL?",a:"Edit, Transfer, Link",b:"Extract, Transform, Load",c:"Enter, Test, Leave",d:"Export, Translate, Log",correct:"b",exp:"ETL: Extraer datos de fuentes, Transformar (limpiar/preparar) y Cargar en destino."},
   {q:"En que fase se limpian los datos?",a:"Extract",b:"Transform",c:"Load",d:"Todas",correct:"b",exp:"La fase Transform es donde se limpian, normalizan y preparan los datos."},
   {q:"Diferencia entre ETL y ELT?",a:"Son iguales",b:"ETL transforma antes de cargar, ELT carga primero y transforma en destino",c:"ELT es mas lento",d:"ETL es mas moderno",correct:"b",exp:"ELT aprovecha el poder del data warehouse para transformar despues de cargar, es mas moderno."},
   {q:"Apache Airflow se usa para:",a:"Almacenar datos",b:"Orquestar y programar pipelines ETL",c:"Crear dashboards",d:"Machine Learning",correct:"b",exp:"Airflow programa, ejecuta y monitorea flujos de trabajo ETL de forma automatizada."},
   {q:"Por que Parquet es preferido como formato de salida?",a:"Es texto plano",b:"Es columnar, comprimido y eficiente para consultas analiticas",c:"Es el mas antiguo",d:"Es el unico que soporta Spark",correct:"b",exp:"Parquet es columnar y comprimido, ideal para consultas que solo necesitan algunas columnas."}]},

  {subjectId:"191281b2-a3bb-4fbd-9a1d-f92443d1be3b",number:12,title:"Data Warehousing: conceptos fundamentales",video:"https://www.youtube.com/watch?v=AHR_7jFCMeY",
   theory:"# Data Warehousing\n\nUn Data Warehouse (DWH) es un repositorio central de datos optimizado para analisis y reportes.\n\n## Diferencias DWH vs Base Operacional\n| Caracteristica | BD Operacional | Data Warehouse |\n|---|---|---|\n| Proposito | Transacciones (OLTP) | Analisis (OLAP) |\n| Consultas | Simples, rapidas | Complejas, agregaciones |\n| Datos | Actuales | Historicos |\n| Normalizacion | Alta (3NF) | Baja (desnormalizada) |\n\n## Esquema Estrella (Star Schema)\nEl modelo mas comun en DWH:\n- **Tabla de hechos** (facts): metricas numericas (ventas, cantidad)\n- **Tablas de dimension**: contexto descriptivo (producto, cliente, fecha)\n\n```\n        dim_cliente\n             |\n dim_fecha - fact_ventas - dim_producto\n             |\n        dim_tienda\n```\n\n## Esquema Copo de Nieve (Snowflake)\nDimensiones normalizadas (dim_ciudad -> dim_pais).\nMas complejo pero ahorra espacio.\n\n## Data Lake vs Data Warehouse\n- **Data Lake**: datos crudos, cualquier formato, schema-on-read\n- **Data Warehouse**: datos limpios, estructurados, schema-on-write\n- **Data Lakehouse**: combinacion de ambos (Delta Lake, Iceberg)\n\n## Herramientas DWH modernas\n- Google BigQuery (serverless)\n- Amazon Redshift\n- Snowflake\n- Azure Synapse\n- Databricks (Lakehouse)",
   quiz:[{q:"Que es un Data Warehouse?",a:"Base de datos operacional",b:"Repositorio central optimizado para analisis",c:"Servidor de archivos",d:"Motor de busqueda",correct:"b",exp:"Un DWH centraliza datos historicos de multiples fuentes y esta optimizado para consultas analiticas."},
   {q:"Que es un esquema estrella?",a:"Base de datos NoSQL",b:"Tabla de hechos central rodeada de tablas de dimension",c:"Un tipo de indice",d:"Base de datos en la nube",correct:"b",exp:"Star Schema tiene una tabla de hechos (metricas) conectada a tablas de dimension (contexto)."},
   {q:"OLTP vs OLAP?",a:"Son lo mismo",b:"OLTP son transacciones, OLAP es analisis",c:"OLAP son transacciones",d:"OLTP es analisis",correct:"b",exp:"OLTP maneja transacciones operacionales; OLAP esta disenado para consultas analiticas complejas."},
   {q:"Data Lake almacena datos:",a:"Solo estructurados",b:"Crudos en cualquier formato (schema-on-read)",c:"Solo en SQL",d:"Solo historicos",correct:"b",exp:"Un Data Lake acepta datos en cualquier formato y el esquema se aplica al leer los datos."},
   {q:"BigQuery de Google es:",a:"Una base NoSQL",b:"Un Data Warehouse serverless con SQL",c:"Un Data Lake",d:"Un motor de streaming",correct:"b",exp:"BigQuery es un DWH serverless que permite analizar petabytes de datos con SQL estandar."}]},

  {subjectId:"191281b2-a3bb-4fbd-9a1d-f92443d1be3b",number:13,title:"Visualizacion de datos masivos",video:"https://www.youtube.com/watch?v=UO98lJQ3QGI",
   theory:"# Visualizacion de Datos Masivos\n\nVisualizar Big Data requiere tecnicas especiales porque los graficos tradicionales no funcionan con millones de puntos.\n\n## Desafios\n- Demasiados puntos para scatter plot\n- Navegador/pantalla no puede renderizar millones de elementos\n- Necesidad de agregar antes de visualizar\n\n## Estrategia 1: Agregar primero\n```python\n# En lugar de graficar 10M de filas\n# Agrupar por dia/semana/mes\ndf_diario = df.groupby(\"fecha\").agg({\"ventas\": \"sum\", \"usuarios\": \"count\"})\ndf_diario.plot()\n```\n\n## Estrategia 2: Muestreo\n```python\n# Tomar muestra representativa\nmuestra = df.sample(frac=0.01, random_state=42)  # 1%\nmuestra.plot.scatter(x=\"edad\", y=\"ingreso\")\n```\n\n## Estrategia 3: Heatmaps y binning\n```python\nimport matplotlib.pyplot as plt\nplt.hexbin(df[\"x\"], df[\"y\"], gridsize=30, cmap=\"YlOrRd\")\nplt.colorbar()\nplt.show()\n```\n\n## Herramientas para Big Data\n- **Apache Superset**: dashboards open-source\n- **Grafana**: monitoreo y metricas\n- **Looker/Data Studio**: Google, conecta a BigQuery\n- **Tableau**: lider en BI\n- **Power BI**: Microsoft, integracion Office\n- **Plotly/Dash**: graficos interactivos Python\n\n## Mejores graficos por tipo de analisis\n- Tendencia temporal: lineas\n- Distribucion: histograma, boxplot\n- Comparacion: barras\n- Relacion: scatter (con muestra), heatmap\n- Composicion: stacked bar, treemap\n- Geoespacial: mapas coropleticos",
   quiz:[{q:"Por que no se puede hacer scatter plot con 10M de puntos?",a:"Python no lo permite",b:"El navegador no puede renderizar millones de elementos",c:"Los puntos se ven mal",d:"Falta memoria siempre",correct:"b",exp:"Renderizar millones de puntos satura el navegador/pantalla, haciendo el grafico ilegible e inutilizable."},
   {q:"Cual es la mejor estrategia antes de visualizar Big Data?",a:"Usar mas RAM",b:"Agregar o muestrear los datos primero",c:"Cambiar de herramienta",d:"Ignorar datos",correct:"b",exp:"Agregar (resumen) o muestrear (subconjunto representativo) reduce los datos a un nivel visualizable."},
   {q:"Que es un heatmap hexagonal (hexbin)?",a:"Un mapa geografico",b:"Divide el area en hexagonos y cuenta puntos en cada uno",c:"Un grafico 3D",d:"Un tipo de tabla",correct:"b",exp:"hexbin crea una cuadricula hexagonal donde el color indica la densidad de puntos en cada celda."},
   {q:"Apache Superset es:",a:"Base de datos",b:"Herramienta open-source para dashboards de BI",c:"Lenguaje de programacion",d:"Servicio de nube",correct:"b",exp:"Superset es una plataforma open-source para explorar y visualizar datos con dashboards interactivos."},
   {q:"Para ver tendencia de ventas en el tiempo, que grafico usar?",a:"Pastel",b:"Lineas",c:"Scatter",d:"Treemap",correct:"b",exp:"Los graficos de lineas son ideales para mostrar tendencias y cambios a lo largo del tiempo."}]},

  {subjectId:"191281b2-a3bb-4fbd-9a1d-f92443d1be3b",number:14,title:"Proyecto: pipeline ETL basico",video:"https://www.youtube.com/watch?v=dvviIUKwH7o",
   theory:"# Proyecto: Pipeline ETL Basico\n\nConstruiremos un pipeline ETL completo que extrae datos de un CSV, los transforma y los carga en formato Parquet.\n\n## Estructura del proyecto\n```\netl_proyecto/\n    extract.py\n    transform.py\n    load.py\n    main.py\n    datos/\n        ventas_raw.csv\n    output/\n```\n\n## Extract (extract.py)\n```python\nimport pandas as pd\n\ndef extraer_datos(ruta):\n    print(\"Extrayendo datos de: \" + ruta)\n    df = pd.read_csv(ruta)\n    print(\"Filas extraidas: \" + str(len(df)))\n    return df\n```\n\n## Transform (transform.py)\n```python\nimport pandas as pd\n\ndef transformar(df):\n    print(\"Transformando datos...\")\n    # Eliminar nulos\n    df = df.dropna(subset=[\"producto\", \"cantidad\", \"precio\"])\n    # Normalizar texto\n    df[\"producto\"] = df[\"producto\"].str.strip().str.lower()\n    # Calcular total\n    df[\"total\"] = df[\"cantidad\"] * df[\"precio\"]\n    # Convertir fecha\n    df[\"fecha\"] = pd.to_datetime(df[\"fecha\"])\n    # Agregar columnas\n    df[\"mes\"] = df[\"fecha\"].dt.month\n    df[\"anio\"] = df[\"fecha\"].dt.year\n    # Eliminar duplicados\n    df = df.drop_duplicates()\n    print(\"Filas despues de limpieza: \" + str(len(df)))\n    return df\n```\n\n## Load (load.py)\n```python\ndef cargar_datos(df, ruta_salida):\n    print(\"Cargando datos a: \" + ruta_salida)\n    df.to_parquet(ruta_salida, index=False)\n    print(\"Pipeline completado\")\n```\n\n## Main (main.py)\n```python\nfrom extract import extraer_datos\nfrom transform import transformar\nfrom load import cargar_datos\nimport time\n\ndef main():\n    inicio = time.time()\n    df_raw = extraer_datos(\"datos/ventas_raw.csv\")\n    df_limpio = transformar(df_raw)\n    cargar_datos(df_limpio, \"output/ventas_limpias.parquet\")\n    duracion = round(time.time() - inicio, 2)\n    print(\"Tiempo total: \" + str(duracion) + \" segundos\")\n\nmain()\n```\n\n## Conceptos aplicados\n- Modularizacion (archivos separados)\n- Funciones con responsabilidad unica\n- Logging basico con print\n- Manejo de tipos de datos\n- Formato de salida optimizado",
   quiz:[{q:"Cuantas fases tiene un pipeline ETL?",a:"2",b:"3: Extract, Transform, Load",c:"4",d:"5",correct:"b",exp:"ETL tiene exactamente 3 fases: Extraer, Transformar y Cargar."},
   {q:"Por que separar cada fase en su propio archivo?",a:"Obligatorio",b:"Modularidad: mas facil de mantener, probar y reutilizar",c:"Mas rapido",d:"Python lo requiere",correct:"b",exp:"La modularizacion permite probar, mantener y reutilizar cada componente de forma independiente."},
   {q:"Que formato de salida es mas eficiente que CSV?",a:"JSON",b:"TXT",c:"Parquet",d:"XML",correct:"c",exp:"Parquet es columnar y comprimido, mucho mas eficiente para almacenamiento y consultas analiticas."},
   {q:"En la fase Transform, que se hace primero?",a:"Calcular metricas",b:"Eliminar nulos y duplicados (limpieza basica)",c:"Cargar datos",d:"Crear graficos",correct:"b",exp:"Primero se limpia (nulos, duplicados, tipos) antes de calcular campos derivados o agregar."},
   {q:"Para que sirve time.time() en el pipeline?",a:"Crear timestamps",b:"Medir cuanto tarda la ejecucion del pipeline",c:"Pausar el programa",d:"Formatear fechas",correct:"b",exp:"Medir el tiempo de ejecucion ayuda a identificar cuellos de botella y optimizar el pipeline."}]},

  {subjectId:"191281b2-a3bb-4fbd-9a1d-f92443d1be3b",number:15,title:"Proyecto: analisis de logs con Spark",video:"https://www.youtube.com/watch?v=_C8kWso4ne4",
   theory:"# Proyecto: Analisis de Logs con Spark\n\nLos logs de servidores generan gigabytes de datos diarios. Spark es ideal para procesarlos.\n\n## Tipo de log (Apache access log)\n```\n192.168.1.1 - - [01/Mar/2026:10:15:32] \"GET /api/users HTTP/1.1\" 200 1234\n```\n\n## Cargar logs en Spark\n```python\nfrom pyspark.sql import SparkSession\nfrom pyspark.sql.functions import col, split, regexp_extract, count, desc\n\nspark = SparkSession.builder.appName(\"LogAnalysis\").getOrCreate()\n\n# Leer logs como texto\nlogs = spark.read.text(\"server_logs/*.log\")\nprint(\"Total lineas: \" + str(logs.count()))\n```\n\n## Parsear con regex\n```python\n# Extraer IP, fecha, metodo, ruta, status\ndf = logs.select(\n    regexp_extract(\"value\", r\"^(\\S+)\", 1).alias(\"ip\"),\n    regexp_extract(\"value\", r\"\\[(.*?)\\]\", 1).alias(\"fecha\"),\n    regexp_extract(\"value\", r'\"(\\S+)', 1).alias(\"metodo\"),\n    regexp_extract(\"value\", r'\"\\S+ (\\S+)', 1).alias(\"ruta\"),\n    regexp_extract(\"value\", r'\" (\\d{3})', 1).alias(\"status\").cast(\"int\")\n)\n```\n\n## Analisis\n```python\n# Top 10 IPs con mas requests\ndf.groupBy(\"ip\").count().orderBy(desc(\"count\")).show(10)\n\n# Errores 4xx y 5xx\nerrores = df.filter((col(\"status\") >= 400))\nerrores.groupBy(\"status\").count().orderBy(desc(\"count\")).show()\n\n# Paginas mas visitadas\ndf.groupBy(\"ruta\").count().orderBy(desc(\"count\")).show(20)\n\n# Requests por hora\ndf.groupBy(\"hora\").count().orderBy(\"hora\").show(24)\n```\n\n## Guardar resultados\n```python\n# Top IPs sospechosas (posible DDoS)\ntop_ips = df.groupBy(\"ip\").count().filter(col(\"count\") > 1000)\ntop_ips.write.csv(\"output/ips_sospechosas\", header=True)\n```\n\n## Casos de uso reales\n- Deteccion de ataques DDoS (IPs con miles de requests)\n- Monitoreo de errores (picos de 500)\n- Analisis de trafico (paginas populares)\n- Deteccion de bots (patrones de User-Agent)",
   quiz:[{q:"Por que usar Spark para analisis de logs?",a:"Es mas facil que Python",b:"Procesa gigabytes/terabytes de logs de forma distribuida",c:"Es la unica opcion",d:"Los logs son pequenos",correct:"b",exp:"Los servidores generan enormes volumenes de logs que necesitan procesamiento distribuido."},
   {q:"regexp_extract() se usa para:",a:"Crear expresiones regulares",b:"Extraer partes especificas del texto usando regex",c:"Reemplazar texto",d:"Validar formato",correct:"b",exp:"regexp_extract permite usar expresiones regulares para extraer campos de texto no estructurado."},
   {q:"Un codigo de estado HTTP 500 indica:",a:"Exito",b:"Redireccion",c:"Error del servidor",d:"No encontrado",correct:"c",exp:"Los codigos 5xx indican errores del servidor, 500 es error interno del servidor."},
   {q:"Como detectar un posible ataque DDoS en logs?",a:"Buscar errores 404",b:"Buscar IPs con un numero inusualmente alto de requests",c:"Revisar paginas lentas",d:"Contar usuarios unicos",correct:"b",exp:"Un DDoS se detecta por IPs que generan miles de requests en poco tiempo, saturando el servidor."},
   {q:"Que ventaja tiene guardar resultados en Parquet vs CSV?",a:"Es mas legible",b:"Compresion columnar, lectura rapida, tipado de datos",c:"Es texto plano",d:"Funciona en Excel",correct:"b",exp:"Parquet ofrece compresion superior, lectura selectiva de columnas y preserva tipos de datos."}]},

  {subjectId:"191281b2-a3bb-4fbd-9a1d-f92443d1be3b",number:16,title:"Repaso final y evaluacion del modulo",video:"https://www.youtube.com/watch?v=bAyrObl7TYE",
   theory:"# Repaso Final - Introduccion a Big Data\n\n## Temas cubiertos\n\n### Bloque 1: Fundamentos (S1-S4)\n- Que es Big Data y las 5 Vs\n- Ecosistema Big Data y herramientas\n- Sistemas de archivos distribuidos (HDFS)\n- Introduccion a SQL para analisis\n\n### Bloque 2: Tecnologias core (S5-S8)\n- NoSQL: documento, clave-valor, columnar, grafo\n- Hadoop: HDFS + MapReduce\n- Apache Spark: RDD, DataFrames, Spark SQL\n- Cloud computing: AWS, GCP, Azure\n\n### Bloque 3: Procesamiento (S9-S13)\n- PySpark: DataFrames distribuidos\n- SQL avanzado: CTEs, Window Functions\n- ETL: Extract, Transform, Load\n- Data Warehousing: Star Schema, OLAP\n- Visualizacion de datos masivos\n\n### Bloque 4: Proyectos (S14-S15)\n- Pipeline ETL completo\n- Analisis de logs con Spark\n\n## Conceptos clave para la evaluacion\n1. Las 5 Vs de Big Data: Volumen, Velocidad, Variedad, Veracidad, Valor\n2. HDFS: bloques de 128MB, 3 replicas, NameNode + DataNode\n3. Spark es 100x mas rapido que MapReduce (procesamiento en memoria)\n4. CAP Theorem: solo 2 de 3 (Consistencia, Disponibilidad, Particiones)\n5. ETL vs ELT: cuando usar cada uno\n6. Star Schema: fact table + dimension tables\n7. PySpark: lazy evaluation, show() para ejecutar\n\n## Que sigue\n- Semestre 2: Machine Learning a escala\n- Semestre 2: Streaming con Kafka y Spark Streaming\n- Semestre 2: Cloud Data Engineering\n\nHas completado los fundamentos de Big Data. Ahora entiendes como se procesan, almacenan y analizan datos a escala.",
   quiz:[{q:"Cuales son las 5 Vs de Big Data?",a:"Velocidad, Virtual, Visible, Valor, Vacio",b:"Volumen, Velocidad, Variedad, Veracidad, Valor",c:"Version, Volumen, Variable, Venta, Vida",d:"Volumen, Vehiculo, Variedad, Vision, Valor",correct:"b",exp:"Las 5 Vs son: Volumen (cantidad), Velocidad (rapidez), Variedad (tipos), Veracidad (calidad), Valor (utilidad)."},
   {q:"Spark procesa en memoria, MapReduce en:",a:"Memoria tambien",b:"Disco (mucho mas lento)",c:"Nube",d:"GPU",correct:"b",exp:"MapReduce escribe resultados intermedios a disco; Spark los mantiene en memoria, siendo hasta 100x mas rapido."},
   {q:"Que es un Star Schema?",a:"Tipo de base NoSQL",b:"Tabla de hechos central rodeada de dimensiones",c:"Formato de archivo",d:"Tipo de consulta SQL",correct:"b",exp:"Star Schema organiza datos con una tabla de hechos (metricas) y tablas de dimension (contexto)."},
   {q:"ETL se usa para:",a:"Crear dashboards",b:"Mover datos de fuentes a destino analitico con transformacion",c:"Solo almacenar datos",d:"Machine Learning",correct:"b",exp:"ETL extrae datos de fuentes, los transforma (limpia/prepara) y los carga en un destino de analisis."},
   {q:"Que herramienta usamos para procesar logs masivos?",a:"Excel",b:"Pandas",c:"PySpark (Apache Spark con Python)",d:"SQL Server",correct:"c",exp:"PySpark permite procesar gigabytes/terabytes de logs de forma distribuida en un cluster."}]}
];

async function post(url, body) {
  const r = await fetch(url, {method:"POST",headers:H,body:JSON.stringify(body)});
  return {status:r.status, data:await r.json()};
}

async function main() {
  console.log("=== Cargando sesiones 9-16 (24 sesiones) ===\n");
  for (const s of sessions) {
    const {status,data} = await post(BASE+"/sessions", {
      subject_id:s.subjectId, number:s.number, title:s.title, video_url:s.video,
      theory_markdown:s.theory, order_index:s.number, estimated_duration_minutes:45, is_active:true
    });
    if (status !== 201) { console.log("  ERR S"+s.number+": "+JSON.stringify(data).substring(0,80)); continue; }
    const sid = Array.isArray(data)?data[0].id:data.id;
    let info = "  S"+s.number+" "+s.title.substring(0,35)+" OK";

    if (s.quiz && s.quiz.length > 0) {
      const {status:qs,data:qd} = await post(BASE+"/quizzes", {
        session_id:sid, title:"Quiz - "+s.title, pass_percentage:70, max_attempts:3, is_active:true
      });
      if (qs === 201) {
        const qid = Array.isArray(qd)?qd[0].id:qd.id;
        for (let i=0;i<s.quiz.length;i++) {
          const q=s.quiz[i];
          await fetch(BASE+"/quiz_questions", {method:"POST",headers:Hm,body:JSON.stringify({
            quiz_id:qid, question_text:q.q, question_type:"multiple_choice",
            options:JSON.stringify([
              {id:"a",text:q.a,is_correct:q.correct==="a"},
              {id:"b",text:q.b,is_correct:q.correct==="b"},
              {id:"c",text:q.c,is_correct:q.correct==="c"},
              {id:"d",text:q.d,is_correct:q.correct==="d"}
            ]),
            explanation:q.exp, points:1, order_index:i+1
          })});
        }
        info += " | Q:"+s.quiz.length;
      }
    }
    console.log(info);
  }
  console.log("\n=== COMPLETADO ===");
}
main().catch(e => console.error(e));
